services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'secret' # Recommended to change this
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    container_name: php
    restart: always
    image: szabacsik/ubuntu_apache_php_phalcon:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
